### ISSUE TITLE
new lockfile configuration option

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#116]
initial proposal is to have a top level configuration option:

```
Lockfile:
	Type: packrat | renv | pkgr
```

When the type is packrat AND library is not set, then install to `packrat/lib/<platform>/<rversion>`

**Comment by dpastoor** [comment]
initially, can no-op renv/pkgr

**Comment by david-lyder** [comment]
**Requirements:**
Support "packrat"-like folder structure (packrat/lib/<platform>/<rversion>) when pkgr.yml file:
1. Does not define "Library"
and
2. Defines Lockfile Type as "packrat"

**Comment by david-lyder** [comment]
**Implementation proposal**
1. Define new type in PkgrConfig to support Lockfile, etc.
2. It's easy and tempting to overwrite cfg.Library if we are in "packrat mode', but it does not feel legit to overwrite viper marshall.  

cfg.Library is called in 3 locations, we can add logic in each location to use cfg.Library or a packrat path, or we can build a function\property to return the appropriate value.  

I lean toward a function in cmd\utils.go, or maybe in structs.go. It may not be a bad pattern to have "property-like" getters and setters in structs.go

**Comment by dpastoor** [comment]
I am wondering if we need such "dynamism" in having a LibraryPath method that would have logic each time it is invoked. It would also require version and platform and/or the RSettings struct, based on your examples, to be carried around externally any place it was called. 

My gut is to say, given that this is a pretty static derivation, why not just do this logic in the constructor and be "done" with it, however that is at odds with how we are currently unmarshalling the cfg struct directly. That said, the more I think about it, per our convo on the phone, the more I'm thinking we may be doing some pre-processing after unmarshalling, but before the struct does anything else (eg variable replacement/injection), so creating an official constructor and doing it there could be a nice stepping stone to that.

**Comment by dpastoor** [comment]
https://github.com/metrumresearchgroup/pkgr/blob/master/cmd/root.go#L108

I could imagine this as instead being something like

```
NewConfig(&cfg)
```

where NewConfig did the unmarshalling, then also started marching through and doing additional refinements, for example, checking if lockfile is of type packrat, and adjusting library, etc.

**Comment by david-lyder** [comment]
I'm good with this idea ... the NewConfig function gives us a central location to make changes after the marshal

**Comment by david-lyder** [comment]
For "pkgr plan", we log fatal if the Library path does not exist. Is it the user's responsibility to create Library path?

**Comment by dpastoor** [comment]
@david-lyder pkgr pattern for install location is: `renv/library/R-<versionstringmajorminor>/platform` - eg `renv/library/R-3.5/x86_64-apple-darwin15.6.0`

**Comment by david-lyder** [comment]
Not sure I understand the comment. There has been no change to the "Library" property for "pkgr". For "packrat", (from the packrat docs) I see an example installation folder of:
/Users/kevin/projects/babynames/packrat/lib/x86_64-apple-darwin13.1.0/3.2.0
which is like:
{some folder}/packrat/lib/{PLATFORM}/{R-VERSION}
Not sure what needs to change ... add the 'R-" in front of R version?

**Comment by dpastoor** [comment]
slip of the tongue, i meant to say that was the renv folder path

**Comment by david-lyder** [comment]
@dpastoor need some clarity on the  expected behavior when using the "renv" type. Thanks.
