### ISSUE TITLE
provide list of packages to install

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#131]
during installation, the default behavior should really only give key information about what the user many need to know to determine if they should intervene and investigate further, vs move forward with installing.

In particular:

* they have a sense of where packages should come from in multi-repo contexts
* they are anticipating a certain new number of packages to be available to install
* there are out of date packages

**Comment by Dreznel** [comment]
It looks like this is already in progress, but it's not assigned to anyone and it was in the backlog. Could we clarify what's left to do, exactly?

**Comment by dpastoor** [comment]
thanks for checking - yes we should move this to implementation complete.

Overall, this is one of those areas that is a bit of a testing grey area, as its not necessarily a change in how pkgr works, just how it logs back to the user. Some people argue these types of things don't even get tested at all, but if not it should get reviewed for whether the new implementation makes sense and is more effective at communicating information (eg I'm going for less info overall, but having it be more relevant to their decision making).
