### ISSUE TITLE
Documentation Request: How to install on Windows?

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/pkgr#133]
I just got a new laptop, and I wanted to evaluate updating my installation method for R packages to `pkgr`.  Windows use appears to be supported as described in #43, but I don't see how to use it.

Can you please update the README instructions to include how to install on Windows?

**Comment by dpastoor** [comment]
hey bill. Yes I can add a note explicitly in the readme. In the meanwhile, the simple answer is, we don't go through any system package management solution on windows (eg chocolatey), so similar to linux, its just about dumping it in a folder thats on your path.

Install steps:

1) go to the latest release https://github.com/metrumresearchgroup/pkgr/releases/latest

2) download the windows tarball

![image](https://user-images.githubusercontent.com/3196313/61797850-38eb1000-adf6-11e9-9685-1aa372004f17.png)

3) extract the windows tarball to a folder on your path, and you're good to go! Its just a single binary file so there is no "installing" to do.


NOTE: if you don't have something set up on your path, my suggested practice is in your home directory create a folder called `apps` and put the binary there. You can then add apps to your path by following https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/ or https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/

**Comment by billdenney** [comment]
Thanks!
