### ISSUE TITLE
Documentation request: pkgr.yml "Lockfile" setting

### ISSUE THREAD

**Issue by Dreznel** [metrumresearchgroup/pkgr#141]
In release v0.5.0-alpha.1, it is specified that Packrat now supports the "Lockfile" attribute in pkgr.yml, but I don't see any documentation for this. I'd like to see documentation in general for how pkgr and Packrat work together.

"39157bd feat: support packrat folder structure for installed packages, use Lockfile attribute in pkgr.yml reference: #116"

**Comment by dpastoor** [comment]
described in https://github.com/metrumresearchgroup/pkgr/wiki/user_manual
