### ISSUE TITLE
update from cache

### ISSUE THREAD

**Issue by dpolhamus** [metrumresearchgroup/pkgr#143]
Maybe related to https://github.com/metrumresearchgroup/pkgr/issues/2

When multiple people are working on different branches I anticipate that, eventually, different sets of packages will end up being installed on different branches.  For example, one user does some DA in one branch, and then another user picks up with modeling by creating a new branch off of the one DA was performed in and adds a bunch of packages from the current tip of CRAN (which may be different than that which the DA scientist was using).

 My current understanding of `pkgr` leads me to believe we'll be tracking the cache in git, so to harmonize across branches it seems reasonable to require a feature that allows you to install all of the highest versions of packages from the cache.  I.e., something like `pkgr install --update --cached`.   I think `pkgr install --update` currently just grabs the highest version from the first `Repo` in which the package is found, correct?

Or maybe instead the correct approach is to use snapshots of CRAN  as the `Repo` that remain static for the duration of a project?

**Comment by dpastoor** [comment]
Dan,

We definitely will _not_ want to track the cache in git, namely binaries are not guaranteed to be portable across systems or changes in a given system, so the cache should only be present locally, and blown away given any changes in system-level dependencies or compilers on said system.

The point of the cache is to provide a central place to leverage _across_ projects on a given system, not necessarily a cache to be used across systems.

This _is_ something on our general roadmap (being able to cache across systems) but is not how the cache works to-date. For example, having an organization cache in an s3 bucket that is metworx compatible so installing from a known repo on a known system can check against that remote cache and pull pre-compiled binaries from there.

**Comment by dpolhamus** [comment]
I see, that makes sense in the context of pointing to a set of hosted binaries.  For whatever reason (stuck in the pkgSetup.R world)  I was thinking the cache contained only the source, but I see now it's split in to `src` or `bin`.

So really the key takeaway here to ensure consistency across branches within a project is that the `Repo` shouldn't change across the course of a project and we will rely on snapshots of CRAN with other other packages that have been "validate" to work alongside that snapshot.

**Comment by dpastoor** [comment]
correct - this strategy (no lockfile or checked in local store) really only works with immutable Repos, which if we use repos we have full control of organizationally, is a good trade-off so we don't check so much in to each repo.
