### ISSUE TITLE
With CRAN URL change, pkgr downloads too many packages

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/pkgr#150]
I just made two changes to my pkgr.yml file:  Added the daff library and updated the CRAN URL to "https://cran.microsoft.com/snapshot/2019-08-15" from the version that was just a couple of days older.

When I ran `pkgr --update install`, it downloaded all my packages again.  This is definitely open for debate, but I think that any repository *named* the same thing should go into the same directory rather than doing it by *name*-*URL hash*.  My hope would have been that it only downloads the packages that are specifically new and needed rather than downloading everything again.

**Comment by dpastoor** [comment]
Thanks Bill, that is actually how it was originally implemented.

The problem that we ran into with that is immediately you run into conflicts if you have two separate projects that both use the name <CRAN> and refer to different url's but use the same cache.

I think the better situation is really in #24 so we just download what you need, and the cache can still stay pristine. That would result in the same scenario in your case (wouldn't download all those existing packages) while also still keeping the cache unique

**Comment by billdenney** [comment]
Yep, I agree that #24 would fix it.  I'll consider this close enough to a duplicate of that and close it.
