### ISSUE TITLE
pkgr clean cache Leaves Empty Directories

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/pkgr#151]
I just ran `pkgr clean cache`, and the empty cache directories were left.  I think that the cache directories that are specific to a repository should be removed.

**Comment by dpastoor** [comment]
agreed

**Comment by Dreznel** [comment]
Acceptance Criteria:
- `pkgr clean cache ` command no longer leaves empty cache directories.

**Comment by billdenney** [comment]
Thanks!
