### ISSUE TITLE
nil pointer error

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/pkgr#159]
I just got the nil pointer error below when I ran pkgr (0.5.0) on Windows 10 with the attached .yml file: [pkgr.yml.txt](https://github.com/metrumresearchgroup/pkgr/files/3571737/pkgr.yml.txt) (.txt added for GitHum to allow attachments).

```
pkgr --update install
INFO[0000] R Version 3.6.1
INFO[0002] found installed packages                      count=253
WARN[0002] Packages not installed by pkgr                packages="[lmtest PKNCA censReg glmmML plm TopicLongTable xpose Rdpack sandwich gbRd formulops latex.makers bsd.report maxLik bdsmatrix miscTools PKdata Rsdtm]"
WARN[0003] error downloading repo r_validated, type: binary, with information: failed fetching PACKAGES file from https://metrumresearchgroup.github.io/r_validated/bin/windows/contrib/3.6/PACKAGES, with status 404 Not Found
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x76788f]

goroutine 51 [running]:
github.com/metrumresearchgroup/pkgr/cran.(*RepoDb).FetchPackages.func1(0xc00016e0f0, 0x3, 0x6, 0x1, 0xc00049e060, 0xc000066170, 0x1)
        /Users/devinpastoor/go/src/github.com/metrumresearchgroup/pkgr/cran/repodb.go:132 +0x10f
created by github.com/metrumresearchgroup/pkgr/cran.(*RepoDb).FetchPackages
        /Users/devinpastoor/go/src/github.com/metrumresearchgroup/pkgr/cran/repodb.go:124 +0x2ea
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x76788f]

goroutine 50 [running]:
github.com/metrumresearchgroup/pkgr/cran.(*RepoDb).FetchPackages.func1(0xc00016e0f0, 0x3, 0x6, 0x1, 0xc00049e060, 0xc000066170, 0x2)
        /Users/devinpastoor/go/src/github.com/metrumresearchgroup/pkgr/cran/repodb.go:132 +0x10f
created by github.com/metrumresearchgroup/pkgr/cran.(*RepoDb).FetchPackages
        /Users/devinpastoor/go/src/github.com/metrumresearchgroup/pkgr/cran/repodb.go:124 +0x2ea

```

**Comment by dpastoor** [comment]
hey bill,

unfortunately cran.microsoft.com is DOWN 😱 

The panic error definitely can get cleaned up to communicate more effectively to the user, but as of now, the "fix" to this is to point to a repo that actually works - namely cran.rstudio.com or otherwise.

I'm hoping that this is an azure hiccup or something other than that is now gone forever.

**Comment by dpastoor** [comment]
to be clear - the error comes from trying to fetch from a repo that is invalid url

**Comment by billdenney** [comment]
That makes sense.  I was guessing that it was some issue with the URL, but I didn't assume that cran.microsoft.com would go down, so I didn't check that path.  (When I first was reporting it, I was using the internet from my phone while in the back of a Lyft, so I thought that it could be an unreliable internet issue, too.)

Given the above, I guess this is a feature request for the more informative error message that you indicate above.

**Comment by billdenney** [comment]
I'm closing this since I think that #229 is the better description of the error and the possible fix.
