### ISSUE TITLE
updating description file should ONLY retain the repo installed from, not the original repo

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#164]
else this causes issues with snapshotting

For example in the original description given:

```
Repository: CRAN
```

after installing from MPN it will look like:

```
Repository: CRAN MPN
```

```
Repository: MPN
```

when detected that already Repository Field exists, it can change to `OriginRepository`

**Comment by Dreznel** [comment]
## Acceptance Criteria:
* For any package P installed by pkgr, the DESCRIPTION file of P should have a "Repository" entry that matches exactly the user-defined name of the repository that pkgr retrieved the package from, with no additional text.
