### ISSUE TITLE
difficult to trace bug when doing multiple R version installs

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#165]
I remember going through this in a live code review, looks like it was never reverted. @Dreznel transitioned an info to a Fatal call, which exits right then, making the rest of the code a no-op.

https://github.com/metrumresearchgroup/pkgr/blame/1e295f9c3ccc76e2167eee848275ccbbbf62865a/cran/pkg_nexus.go#L45

Currently trying to debug a situation on windows where running pkgr plan/install on multiple versions of R consecutively to build binaries and the second R version fails with this error:

```
PS C:\Users\DevinPastoor\Documents\pkgrbuilder\3.5\2019-10-04> pkgr plan                                                                                           INFO[0000] Installation would launch 8 workers                                                                                                                     INFO[0000] R Version 3.5.3                                                                                                                                         INFO[0000] found installed packages                      count=0                                                                                                   FATA[0000] error downloading repo information from: MPN:https://mpn.metworx.com/snapshots/stable/2019-10-04  
```

If I change the name to MPN2, it proceeds correctly, so something is going wrong decoding the cache. This doesn't completely make sense as the Hash for the cache does use the R version explicitly https://github.com/metrumresearchgroup/pkgr/blob/master/cran/repodb.go

Unfortunately, this error is being swallowed until we do a new build

**Comment by Dreznel** [comment]
Looks like this is done?
