### ISSUE TITLE
Why isn't mrgsolve 0.10 installed on Windows?

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/pkgr#168]
With the attached pkgr.yml file (rename from .txt to .yml) on Windows, I do not get mrgsolve 0.10 even though it is on the CRAN mirror provided.  Any ideas why it is not installed when running `pkgr --update install`?  As additional information, I already have mrgsolve 0.9.2 installed by pkgr.

I don't know how to check this, but might it be doing a lexicographical instead of version number sort to determine what is new?

[pkgr.txt](https://github.com/metrumresearchgroup/pkgr/files/3740420/pkgr.txt)

**Comment by kylebaron** [comment]
@billdenney It looks like CRAN hasn't built the windows binary for r-release yet.

https://cran.r-project.org/package=mrgsolve

Not sure if it has to get checked on windows r-release before they build it?

**Comment by billdenney** [comment]
Ahh, I didn't know that pkgr required binaries for windows.  I thought that it would build them if not available.

Perhaps a notification from `pkgr` that a source package is available which is newer would be a useful message to receive.

**Comment by billdenney** [comment]
Whoops, thanks for the reminder of the "Type: source" option!

And, thanks for the detailed explanation of the rest of the info.  Everything you say makes sense.  I'll leave the issue open for your consideration to close or not (I'm fine with either).

To make the revised potential feature specific:  For packages installed from binaries (not source), check the source version.  If the source version is greater t than the binary version, issue a message that "The binary version of <pkgname> is being installed, but a newer source version is available.  To install from source, please add the customization 'Type: source' for that package."

**Comment by dpastoor** [comment]
yup, there are also things like - if I update to a different snapshot what would be different, if I switched to different repo (eg on REPO2 mrgsolve is v0.11.0 OMG).

I'm hoping we can get some support to do a funded "dev-focused" push in 2020 that gives more tools to power users around that type of inspection and "decision-making"
