### ISSUE TITLE
in install message list number of remaining packages 

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#171]
As a progress bar, per #129 is not really feasible with the logging, this can at least give a sense of what is remaining

```
INFO[0242] Successfully Installed                        package=stringr repo=MPN version=1.4.0
```

to now

```
INFO[0242] Successfully Installed                        package=stringr repo=MPN version=1.4.0 remaining=8
```

**Comment by Dreznel** [comment]
## Acceptance Criteria
* pkgr lists a "remaining packages" count in the logs after each package is successfully installed.
* This information should be logged at an Info level.
