### ISSUE TITLE
Library should be created if does not exist

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#173]
This is a major request that have gotten numerous times. The original behavior was to error of the library did not exist, for two reasons:

1) we didn't have to worry about the permissions of that lib folder, that was up to the user to make sure was correct.

2) they couldn't accidentally make a lib in a place they weren't expecting

This has proven to be much less of an issue, and instead more painful to have to go make it yourself first, lots of

mkdir <lib> & pkgr install... 

## proposed change

* new top level parameter (accessible via command line and yml file) called `Strict` with a default of false

If strict is set to true, then the Lib must be created, else it will create. This will also position use to be able to tune other more consequential changes in the future. 

## Testing

- install pkg to lib folder when exists or not exists with strict on/off
- if strict off or folder exists should install, if strict on and folder doesn't exist should error with a informative message

**Comment by Dreznel** [comment]
Counting the info under "proposed change" as Acceptance Criteria.

**Comment by Dreznel** [comment]
A couple of questions as I'm working on this:

* Should `pkgr plan` indicate that the library will be created? I'm assuming yes.
* If the Library is created but a package fails to install, should the library be deleted? Assuming yes.

@dpastoor please confirm. I'm trying to determine whether or not I should store a "libraryCreated" variable in installPlan.

**Comment by dpastoor** [comment]
hmm good questions.

I think both of these are reasonable choices and would proceed forward as such.
