### ISSUE TITLE
logging option to delete existing log file

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#18]
especially helpful if running commands successively in a testing context. 

Default should remain to keep the same file, as it provides a comprehensive audit log.

## considerations

* [ ] decouple file log separately for installation vs planning
	* plans do not need to log to the log file by default

**Comment by Dreznel** [comment]
## Proposed Acceptance Criteria:

* Logging options can be set in the config file to do one of the following
    * **default**: append to the existing log file without ever deleting it
    * delete existing log whenever a pkgr command is executed
* Logging option is created to control whether logs all go to one file, or whether pkgr install gets its own log file.
    * **default**: all pkgr commands go to a single log file.
    * optionally, the user can use the config file to indicate a separate log file, which is then used exclusively for logs from pkgr install commands.
* Code is modified to prevent pkgr plan from logging to file.
    * logging option is created to override this behavior and allow pkgr plan to log to file.

**Comment by dpastoor** [comment]
yes these look great - how do you plan on setting the api in the config file?
