### ISSUE TITLE
does the order of the packages list matter?

### ISSUE THREAD

**Issue by janelleh** [metrumresearchgroup/pkgr#213]
This may be a moot point with the way that you have created pkgr compared to the pkgSetup.R script, but -- in the past, we have had issues where one package will install a dependency which is an older version, then a next package with the same dependency fails installation because it needs a newer version than what has been installed. Or vice versa. Off the top of my head Rcpp has given me this problem.

So my question is - does the order of packages matter, in that they are installed top down in the order listed in the yaml script? If so, maybe make a note of that, in the same way that you made a note that "order matters" for the repos.

I haven't run into the problem in a long time, so there may not be any issues with current package versions, but I figured I would bring it to your guys's attention.

**Comment by dpastoor** [comment]
Nope order does not matter. Pkgr inspects your entire dependency graph and solves it to figure out the correct order to only install a package once. So like first all packages with no dependencies, then ones that only depend on those with 0 on upward so a package will only attempt be be installed after all it's dependencies are installed

**Comment by janelleh** [comment]
Excellent, thanks. @kyleb also gave a nice explanation of the old issues with pkgSetup in the thread here: 

https://metrumrg.slack.com/archives/C5WLDHR0W/p1578433540012000
