### ISSUE TITLE
rmarkdown packages in default yaml file - related to @samc's issue here: https://ghe.metrumrg.com/templates/msproject/issues/4

### ISSUE THREAD

**Issue by janelleh** [metrumresearchgroup/pkgr#215]
I created a new Rmarkdown file, but I hadn't installed dependancies yet. It asked me:

![Screen Shot 2020-01-08 at 10 18 50 AM](https://user-images.githubusercontent.com/18706376/71989863-67bc3d80-3200-11ea-96d0-15f8602b4cb4.png)

First question - if clicking yes, would RStudio pull these packages from cran and install into the user library? That is not good, we want to only use packages from the mpn. 

Second - I see that @samc also noticed this in issue here: https://ghe.metrumrg.com/templates/msproject/issues/4, and the issue was resolved and closed, but as of yesterday these two packages were not in the default yaml file from the template here: https://ghe.metrumrg.com/templates/msproject/releases. Only tidyverse and mrgsolve were:

```
Version: 1

Packages:
  - tidyverse
  - mrgsolve

Repos:
  - MPN: https://mpn.metworx.com/snapshots/stable/2019-12-02/

Lockfile:
    Type: renv
```

**Comment by dpastoor** [comment]
Yes looks like we need to cut a new template for release. Those changes are I'm the master branch. You can add those two deps and re run pkgr install and that will add them!

**Comment by janelleh** [comment]
Yes, I did that. Just want to make sure its put into the new template.
Thanks!


Janelle Lennie, MS | Research Associate

Metrum Research Group

2 Tunxis Road | Tariffville, CT 06081

p: 978-886-4462 | e: janelleh@metrumrg.com

<https://info.metrumrg.com/contact>
<https://www.linkedin.com/company/metrum-research-group/>
<https://twitter.com/MetrumRG>
