### ISSUE TITLE
pkgr load cli command

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#228]
loading all pkgs in a library as a sanity check on the fact that all are successfully installed (at least enough to load) can help catch some compilation and runtime bugs that don't present during installation.

In addition, switching R versions, workflow types, or other situations where the binaries have been on the system but are stale can be checked.

## expected behavior

to run all user defined packages in Packages

```
pkgr load
```

will run threads x 2 (since there are some definite IO bottlencecks) where in each subprocess will run the equivalent of

```
R -e "library(<pkg>)"
```

and capture the stdout, stderr, and error code and return normal logrus printed logs that contain the information specified in the json section below.

By default, all successful packages should log a success at the Debug level, Failed packages should present with an Error level, and at the end a summary statement at the info level providing the metadata + a summary

```
INFO[9999] "packages loaded"  checked=120 success = 120 failure=0
```

Hence, for a successful check, the log should be very quiet, however can see the individual results for each that would look like:

```
DEBU[9999] "dplyr"    version="0.8.4" path=... exitcode=0 stderr=... stdout=...
```

### all

```
pkgr load --all
```

will load _all_ packages in the dependency tree, not just the user defined packages

### json

```
pkgr load --json
```

At the _end_ it will return a **single** json object 

```json
{
  metadata: {
   rpath: path/to/R,
   r_version: "3.6.2",
   libpaths: [
      "path/to/lib",
      "other/path"
   ] 
  },
  results: [
    {
      package: "dplyr",
      version: "0.8.4",
      exit_code: 0,
      stderr: "",
      stdout: "",
      path: "path/to/install/folder"
    },
    {
      package: "tidyr",
      version: "1.0.0",
      exit_code: 0,
      stderr: "",
      stdout: "",
      path: "path/to/install/folder"
    },
  ]
}
```

note: there is no equivalent to getting all the runtime libpaths as of yet, this is not just the library per the install, but actually how the R session will see the libraries when its launched. Will need to parse a call to `.libPaths()` to get that.

## additional behaviors:

For install, pkgr by default starts in a highly isolated mode, when this launches, it should launch as the *user* would interact, so _not_ a --vanilla --slave --noprofile, etc session used when installing pkgs. 

## future considerations

should be able to provide a command line flag to change the wd from where the R session will start (to appropriately capture separate .Rprofile's or other things that are important to control where the R session launches, not where the pkgr.yml file lives).

**Comment by Dreznel** [comment]
I see you addressed this in "future considerations", but I want to make it explicit.

> note: there is no equivalent to getting all the runtime libpaths as of yet, **_this is not just the library per the install_**, but actually how the R session will see the libraries when its launched. Will need to parse a call to .libPaths() to get that.

If we're not testing solely the environment that lives in the pkgr-specified `Library`, then I don't understand what this command should be doing. The user could theoretically launch their R session from anywhere and still use pkgr's Library -- it comes down to what's in their .Rprofile. We can't predict what will be in a user's .Rprofile, and we can't predict where a user will launch the session from, so I propose this:

- As part of this feature, we assume by default that the user will launch their R Session from the same directory as their pkgr.yml file.
- We provide a `--from` flag to let users override this default value.
- We do not make `--from` readable from the config file.
