### ISSUE TITLE
Pkgr will enable users to specify whether or not to install/update “recommended” packages

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#234]
## Summary

* Pkgr should provide a user-configurable option that directs whether or not to include “Recommended” packages in its installation plan.
* If no option is specified, pkgr should include installations and updates of “Recommended” packages.
* When “recommended” packages are included, pkgr should only install “recommended” packages that are specified as user packages, or that are in the dependency tree of user packages.

test_tags: recommended

---
### Original details:
the recommended packages shift over time with CRAN, and are also captured in MPN snapshots. Right now pkgr will install those as they will be detected in the system folder, unless they are explicitly set as a top level dependency.

By setting in the pkgr.yml `Recommended: true` this would also force installing all recommended packages.

This should be (hopefully) be as simple as adding the list of recommended packages to the packages slice before solving the rest of the install plan

**Comment by Dreznel** [comment]
It might be good to also log when recommended packages are detected as a dependency

**Comment by dpastoor** [comment]
@Dreznel can we please update this issue with a link to final implementation/spec and make sure we also update docs. Aka we should provide details in the user guide around `NoRecommended: true/false`

**Comment by dpastoor** [comment]
@Dreznel is this done?

**Comment by Dreznel** [comment]
This was in reference to #240, right?

I haven't made the documentation on this yet but I'll get on it so we can close this out.

**Comment by Dreznel** [comment]
@dpastoor I changed the document in a few places, but here are the details:

https://github.com/metrumresearchgroup/pkgr/wiki/user_manual#r-base-and-recommended-packages
