### ISSUE TITLE
all things that could be paths should attempt to expand ~

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#235]
On initial parsing, the following should attempt to be expanded:

* library
* Repo paths, incase they are local repos rather than html

```
Library: ~/rpkgs
```

or 

```
Repos:
- local: "~/crandbs/somedb"
```

**Comment by Dreznel** [comment]
@dpastoor 

This wasn't on my radar, but we still want this for the March release right?

**Comment by dpastoor** [comment]
yes please.

**Comment by Dreznel** [comment]
This is done and can be closed.
