### ISSUE TITLE
Pkgr lockfile option setting does not respect working directory of pkgr command

### ISSUE THREAD

**Issue by Dreznel** [metrumresearchgroup/pkgr#250]
I need to look into this more, but here's the steps to repeat:

Project A:
* Has pkgr.yml with renv lockfile setting.

Project B: 
* Does not have pkgr.yml

From Project B's directory, run `pkgr install --config=projectA/pkgr.yml`. I suspect you will see packages installed to the renv folder in Project A, not Project B as would be expected.

**Comment by dpastoor** [comment]
this is actually working as intended, but probably not what _you_ intended.

In particular, the config file is the root of any action, not the executing directory. So by saying --config=... you are saying run relative to that. Hence the renv path derivation will come up with a path from projectA. You would need to manually specify a library path to wherever else you want to install via --library if you want to override that behavior
