### ISSUE TITLE
Unclear Error Message: expected a map, got 'string'

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/pkgr#316]
With the attached .yml file ([pkgr.txt](https://github.com/metrumresearchgroup/pkgr/files/5548490/pkgr.txt)), I got the error below:

```
>pkgr --update install
FATA[0000] error parsing pkgr.yml: 1 error(s) decoding:

* 'Customizations.Packages[0][Type]' expected a map, got 'string'
```

It appears that I'm doing something wrong in this section, but it's not immediately clear what:

```
Customizations:
  Packages:
    - metrumrg:
      Type: source
    # Work around https://github.com/r-lib/systemfonts/issues/53
    - systemfonts:
      Repo: CRAN_old
```

The error seems to point to the `Type: source`, but removing that didn't fix the issue.

This is on Windows 10 with pkgr version 1.3.0.

**Comment by dpastoor** [comment]
blasted yaml formatting strikes again. The indentation is such that its parsing wrong

What is going on is with yaml when you have those arrays, subitems (eg type) need 2 more spaces, or they're seen as new items

Give this a try:

```diff
Customizations:
  Packages:
    - metrumrg:
-     Type: source
+       Type: source
    # Work around https://github.com/r-lib/systemfonts/issues/53
    - systemfonts:
-     Repo: CRAN_old
+       Repo: CRAN_old

```

**Comment by billdenney** [comment]
Thanks!
