### ISSUE TITLE
Really minor feature request: Add "--version" command line flag

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/pkgr#353]
I just typed `pkgr --version` to see if I was up to date.

It gave an error that didn't show the version (`Error: unknown flag: --version`) and then showed the help with no version number.

When I just typed `pkgr` at the command line, the first line of output was the version.

The request is:

Can you add a `--version` flag?

I think that for preference it will either just show the first line of the output of `pkgr` or if you want something even simpler to maintain just show the output of `pkgr`.  The only real difference is that if `--version` were given, then I would think all other flags and commands would be ignored (probably with a warning if something else were specified).

**Comment by dpastoor** [comment]
@billdenney got around to it finally. will cut a prerelease hopefully by end of weekend

**Comment by kyleam** [comment]
Looks like this came in with 6dd9c3ee (feat: add version flags --version and -v, 2021-07-17) and is part of the v3.0.0 release, so I'll close this.
