### ISSUE TITLE
Add  go.uber.org/automaxprocs to cmd/pkgr/main.go to respect namespace limits

### ISSUE THREAD

**Issue by elisarver** [metrumresearchgroup/pkgr#384]
This is primarily for build systems, but also any other system with `cgroup` CPU quotas. It will prevent the application from parallelizing itself beyond the limits of a given container, to the point where the program is given evermore fractional time-slices.

**Comment by kyleam** [comment]
I believe this was addressed by #385.  @elisarver, please reopen if I'm mistaken.
