### ISSUE TITLE
windows compat

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#43]
At minimum need to adjust the executable commands to `R` becomes `R.exe` Potentially could do so via `https://github.com/metrumresearchgroup/pkgr/blob/master/rcmd/Rsettings.go` and using a custom windows/other build _or_ do a runtime check.

probably want to use a custom build tag.

**Comment by Dreznel** [comment]
This feels more like an epic to me, but I'm not sure how far we are from completing this.

## Proposed Acceptance Criteria:
* All pkgr commands run properly as expected on windows machines. These commands are:
    * pkgr plan
    * pkgr install
    * pkgr show
    * pkgr clean
    * pkgr inspect
    * pkgr experiment
    * pkgr clean
        * pkgr clean cache
        * pkgr clean pkgdbs

## Alternative Acceptance Criteria
* pkgr install and pkgr plan work properly on Windows
* pkgr commands that are not officially supported on Windows are documented
