### ISSUE TITLE
more user feedback over whats going on when pkg downloading

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#47]
especially on a fresh machine when installing large package sets it seems to hang, when in reality its downloading pkgs. Currently the information is only at the debug level so should at minimum give an info level notice that packages are starting to download, else potentially promote pkg downloading to an info level activity.

**Comment by dpastoor** [comment]
before implement complete we'll need to downgrade the download message to a debug. I think given it will make more sense to see what its about to do in case it hangs, rather than just being blank, at an info level show the downloading pkg... then at debug level a download complete message.

**Comment by Dreznel** [comment]
@dpastoor see [this commit](https://github.com/metrumresearchgroup/pkgr/pull/52/commits/267afa9755fda9f094998b180741d7751230fd9b), which is currently living in PR #52 .

**Comment by dpastoor** [comment]
Thanks, I'm thinking do you mind inverting the info/debug so info is for downloading..., and debug is for downloaded.
