### ISSUE TITLE
pkgr clean fails if non-directory file present

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#67]
```
 ~/rpkgs  pkgr clean cache --binaries-only                                           Wed Apr  3 16:48:49 2019
INFO[0000] clearing binary files only from the cache
ERRO[0000] open pkgcache/.DS_Store/: not a directory
```

**Comment by Dreznel** [comment]
Can you recreate this with a "Trace" enabled, or provide the config file and the exact location of the .DS_Store file?

When I run `pkgr clean cache --binaries-only` on my machine with a .DS_Store file in every folder and subfolder of the cache as defined in pkgr.config, the command still works and clears out everything properly.

**Comment by dpastoor** [comment]
couldn't reproduce, so for now will close
