### ISSUE TITLE
pkgr install --update option

### ISSUE THREAD

**Issue by Dreznel** [metrumresearchgroup/pkgr#69]
Create an update option for `pkgr install` that allows users to update outdated packages listed in their pkgr.yml file during the installation process.

* By default, pkgr should not update outdated packages
* With this option set, pkgr should attempt to update the outdated packages, but leave the current installation if the update-installation fails.
* For now, we assume that the user either updates everything or updates nothing -- we do not need to allow them to update specific packages.

# Validation Criteria

Implemented in #78, tested in #74 

##  If update operation fails, pkgr reinstates the previously-installed version.

Implemented in #78

**Comment by dpastoor** [comment]
closing as so closely aligned to #74 that can use that for validation records
