### ISSUE TITLE
pkgr plan supports use of update flag/setting

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#74]
similar to #69 any install activity should also be supported via plan to see what would happen without needing to actually perform the install command.

# validation requirements

## update argument overrides config
Implemented in: #78 
#### automated tests:
N/A
#### manual tests:
* `pkgr plan` on integration_tests/outdated-packages-no-update should not update already installed packages

![image](https://user-images.githubusercontent.com/3196313/56843137-1e42e280-686b-11e9-8017-2ad7c8f6bbdf.png)

* `pkgr plan --update` on integration_tests/outdated-packages-no-update should update outdated packages 

![image](https://user-images.githubusercontent.com/3196313/56843163-4c282700-686b-11e9-9a4f-163c76b5a209.png)

## running `pkgr plan --update` (or the equivalent using the config) will list the packages that will be updated, as well as what version they are currently on and what they will update to.

Implemented in: #78 
#### automated tests:
N/A
#### manual tests:
* `pkgr plan --update` on integration_tests/outdated_packages

![image](https://user-images.githubusercontent.com/3196313/56842986-7aa50280-6869-11e9-8b2d-d58719d3f12e.png)

## running `pkgr plan` without the update setting will warn you about outdated packages

Implemented in: #78 
#### automated tests:
N/A
#### manual tests:
* `pkgr plan` on integration_tests/outdated-packages-no-update should show outdated packages as a warning
* `pkgr plan --update` on integration_tests/outdated-packages-no-update should show outdated packages to be upgraded as info

![image](https://user-images.githubusercontent.com/3196313/56843057-36663200-686a-11e9-9701-734e96d50969.png)

**Comment by Dreznel** [comment]
Plan  _does_ presently list outdated packages as warnings regardless of what options you pass in, but I will change this to make it more explicit.

**Comment by dpastoor** [comment]
after correction for not trying to open non-folder elements in the package library to fail DESCRIPTION, this is complete

**Comment by dpastoor** [comment]
fixed WARNING about missing DESCRIPTION from non-directory file in the package library (in the testing case a .gitignore).

functionality is good to go!
