### ISSUE TITLE
update should also update dependencies

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#77]
issue with devtools install when using --update, showing that an out-of-date dependency causes an install failure

```
ERRO[0022] cmd output                                    exitCode=1 package=devtools stderr="* installing *source* package ‘devtools’ ...\n** package ‘devtools’ successfully unpacked and MD5 sums checked\n** R\n** inst\n** tests\n** byte-compile and prepare package for lazy loading\nError in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : \n  namespace ‘fs’ 1.1.0 is being loaded, but >= 1.2.0 is required\nERROR: lazy loading failed for package ‘devtools’\n* removing ‘/private/var/folders/g_/0948z6350756j3yly26_zqnr0000gn/T/devtools’\n" stdout=
```

when tracing back upwards can see

```
INFO[0016] package already installed                     package=fs
```

and all the way up to the outdated package found message, only outdated top level packages present.

**Comment by Dreznel** [comment]
Can you provide a sample environment (in a zip or something) that recreates this issue you saw?

Based on what I know, **all** packages that are already installed are checked for outdatedness when you run install --update. Following this, here's my train of thought as to why this should already work:

1. The desired behavior of pkgr is to only install the latest versions of any package. 
    * We have not yet built in functionality for installing old packages, and we have deemed that out of scope for this task.
2. It follows from (1) that we expect packages to only depend on the latest versions of other packages.
3. If pkgr scans every installed package for outdatedness prior to installing, then it shouldn't be possible for dependencies to remain out of date in a normal, CRAN-ish space, unless 1/2 are not true.
4. An example:
    * If package A is dependent on package DEP, and package A is installed, then package DEP is installed. 
    * If A is outdated, then the newest version of A should depend on the most recent version of DEP. 
    * When we scan all packages for outdatedness, package A will be and primed for reinstallation. Package DEP will be flagged and primed as well iff the latest version is not already installed.
    * Package installation should proceed as normal from there.

**Comment by Dreznel** [comment]
commit ddd3550 makes the functionality as described above.

**Comment by dpastoor** [comment]
tested in #74, where crayon is an outdated dep only (not user package) and is shown to be flagged for update
