### ISSUE TITLE
potential bug: dependencies not downloaded from specific repository

### ISSUE THREAD

**Issue by Dreznel** [metrumresearchgroup/pkgr#82]
Example case:

```
Version: 1

Packages:
  - rmarkdown
  - shiny
  - devtools
  - mrgsolve

Repos:
  - r_validated: "https://metrumresearchgroup.github.io/r_validated"
  - CRAN-Micro: "https://cran.microsoft.com/snapshot/2018-11-18"
  - CRAN: "https://cran.rstudio.com"

Library: "test-library"

Customizations:
  Packages:
    - shiny:
        Repo: CRAN
```

Shiny will be installed from CRAN, but any of Shiny's dependencies will come from CRAN-Micro. This may not be an issue, but this is unintuitive for the users.

**Comment by Dreznel** [comment]
@dpastoor

**Comment by dpastoor** [comment]
The point is that R tooling will always target the first repo that provides the needed dependencies. There is only so far down the rabbit hole of customization we can go. If someone really needs all dependencies for shiny to also come from CRAN even if in CRAN-micro they can either change the order so CRAN takes precedence or set customizations for all dependencies as well to specify the repo.

At the moment, my current philosophical take is I do not yet want to support something like:

```
Customizations:
   Packages:
     - shiny:
          Repo: CRAN
          Deps: ... # do something to specify to try to force deps from same repo or something
```

as there are too many nuances - what if not all deps are available at that repo, do you fully go recursively, etc.

To that end, this is definitely not a bug, its behaving exactly how it was designed. Whether people will want the dependency behavior we will see.
