### ISSUE TITLE
bug: pkgdb cache not stored in user-specified cache

### ISSUE THREAD

**Issue by Dreznel** [metrumresearchgroup/pkgr#84]
pkgdbs are still stored in `~/Library/pkgr/r_packagedb_caches` even when the "Caches" option is set in pkgr.yml.

**Comment by dpastoor** [comment]
the cache is the package cache, not the repodb cache, so this is not a bug. There shouldn't really be a reason for the user to specify custom cache dirs for the repodb/pkgnexus
