### ISSUE TITLE
inject R install location to system Path if RPath is specified

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#95]
On isolated systems, some packages fail to compile with an error that they cannot find R_HOME. 

example:

http://www.stats.ox.ac.uk/~snijders/siena/siena_r.htm

this is likely due to some funky code, but nothing we can do about that. The workaround _should_ be that we should inject the R directory to $PATH before the subprocess starts and then should be good to go.

**Comment by dpastoor** [comment]
install.go in rmd, inject into the envVars

**Comment by david-lyder** [comment]
There is this function in rcmd config.go "configureEnv" that would be a good place to set the R path.
There is a TODO related to ordering: 
 // TODO: determine if using globalenvvars as a map could cause subtle bug given ordering precedence
I am concerned and will look into deterministic ordering for the map (or use another object)

**Comment by dpastoor** [comment]
yes plz. maps are _non-deterministically_ returned. You might want a custom data structure with like an get/add/exists/rm/ToString methods that maintains the key/value relationship but also can be toString'd to the key=val needs the environment variables have etc

Thanks for noticing, this would be great safety-wise to implement as well
