### ISSUE TITLE
add/rm packages directly from the command line

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#96]
# validation requirements

## can add a package from cli

Implemented in: #102 

#### automated tests:
N/A
## user is alerted if package already exists when trying to add

Implemented in: #102 

#### automated tests:

N/A

#### manual tests:

* ran `add` with pkg `R6` on integration_tests/simple, expecting info message

**Comment by david-lyder** [comment]
Test cases:
1. View usage/help for both add and remove.  Expect long and short description.
2. Add a single package, without --install. Expect pkgr.yml file to have new package in Packages section.
3. Remove a single package. Expect package to not be in Packages section of pkgr.yml file.
4. Add multiple packages, without --install. Expect pkgr.yml file to have new packages in Packages section.
5. Remove a multiple packages. Expect packages to not be in Packages section of pkgr.yml file.
6. Add a single package, with --install. Expect pkgr.yml file to have new package in Packages section and package folder to exist in test-library folder.
7. Add a multiple packages, with --install. Expect pkgr.yml file to have new packages in Packages section and package folders to exist in test-library folder.

Note: "remove" does not remove package folders from test-library. If folders exist, they must be manually removed to test "--install"

**Comment by david-lyder** [comment]
Test 1. add and remove usage:
<img width="1027" alt="Screen Shot 2019-05-24 at 11 31 52 AM" src="https://user-images.githubusercontent.com/47984902/58339469-aa6b0a00-7e17-11e9-8ee0-24f005383558.png">

<img width="1027" alt="Screen Shot 2019-05-24 at 11 34 11 AM" src="https://user-images.githubusercontent.com/47984902/58339578-e605d400-7e17-11e9-957e-39104d5d3ef0.png">

**Comment by david-lyder** [comment]
Test 2: Add a single package, without --install. Expect pkgr.yml file to have new package in Packages section.
<img width="1025" alt="Screen Shot 2019-05-24 at 12 06 16 PM" src="https://user-images.githubusercontent.com/47984902/58341525-6d554680-7e1c-11e9-8208-596e48982f5f.png">

**Comment by david-lyder** [comment]
Test 3: Remove a single package. Expect package to not be in Packages section of pkgr.yml file.
<img width="1025" alt="Screen Shot 2019-05-24 at 12 07 54 PM" src="https://user-images.githubusercontent.com/47984902/58341613-a4c3f300-7e1c-11e9-9791-cb8f5fa6637c.png">

**Comment by david-lyder** [comment]
Test 4: Add multiple packages, without --install. Expect pkgr.yml file to have new packages in Packages section.
<img width="1025" alt="Screen Shot 2019-05-24 at 12 10 17 PM" src="https://user-images.githubusercontent.com/47984902/58341751-f8364100-7e1c-11e9-8005-a14d85e16214.png">

**Comment by david-lyder** [comment]
Test 5: Remove a multiple packages. Expect packages to not be in Packages section of pkgr.yml file.
<img width="1025" alt="Screen Shot 2019-05-24 at 1 34 25 PM" src="https://user-images.githubusercontent.com/47984902/58346371-ba3f1a00-7e28-11e9-8844-913b04db7642.png">

**Comment by david-lyder** [comment]
Add a single package, with --install. Expect pkgr.yml file to have new package in Packages section and package folder to exist in test-library folder.
<img width="1025" alt="Screen Shot 2019-05-24 at 1 37 10 PM" src="https://user-images.githubusercontent.com/47984902/58346503-1f930b00-7e29-11e9-90c2-4469c48465cc.png">

<img width="1025" alt="Screen Shot 2019-05-24 at 1 38 21 PM" src="https://user-images.githubusercontent.com/47984902/58346538-3b96ac80-7e29-11e9-9db4-2e96d32d0dac.png">

<img width="1005" alt="Screen Shot 2019-05-24 at 1 39 05 PM" src="https://user-images.githubusercontent.com/47984902/58346560-510bd680-7e29-11e9-899b-98987e047172.png">

**Comment by david-lyder** [comment]
Test 7: Add a multiple packages, with --install. Expect pkgr.yml file to have new packages in Packages section and package folders to exist in test-library folder.
<img width="1005" alt="Screen Shot 2019-05-24 at 1 40 52 PM" src="https://user-images.githubusercontent.com/47984902/58346676-a34cf780-7e29-11e9-9bc8-2666fa343c1c.png">

<img width="1005" alt="Screen Shot 2019-05-24 at 1 42 20 PM" src="https://user-images.githubusercontent.com/47984902/58346727-c8da0100-7e29-11e9-9cfa-c185e6f8889b.png">

<img width="1005" alt="Screen Shot 2019-05-24 at 1 43 12 PM" src="https://user-images.githubusercontent.com/47984902/58346766-e5763900-7e29-11e9-9e0d-b0ac71d6f83f.png">

**Comment by david-lyder** [comment]
Test 8: Add the same package more than once. Expect no-operation and messaging.
<img width="1005" alt="Screen Shot 2019-05-24 at 1 45 59 PM" src="https://user-images.githubusercontent.com/47984902/58346897-561d5580-7e2a-11e9-8dae-41db79fb5500.png">

**Comment by david-lyder** [comment]
Test 9: . Remove the same package more than once. Expect no-operation and no messaging.
<img width="1005" alt="Screen Shot 2019-05-24 at 1 49 09 PM" src="https://user-images.githubusercontent.com/47984902/58347037-bf9d6400-7e2a-11e9-815c-41ef57a97bcb.png">

**Comment by david-lyder** [comment]
Test 10: Run "go test" that exercises end-to-end "add" and "remove" test.
The file "add_test.go" contains a test named "Test_rAdd" that adds and removes a package using the "simple" setup in the integration test folder.

<img width="1005" alt="Screen Shot 2019-05-24 at 1 55 16 PM" src="https://user-images.githubusercontent.com/47984902/58347674-751ce700-7e2c-11e9-8d39-2edd8c3a37c4.png">

**Comment by dpastoor** [comment]
good work! looks ready to merge #102
